# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_3BLid456-E4KtQjIEK9dQ0kJvuMbvQ
"""

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split

# ==============================================================================
# PHASE 1: MASSIVE DATA ENGINE (100,000 Samples)
# Principle: Big Data for High Variance Training
# ==============================================================================
def generate_massive_dataset(n=100000):
    np.random.seed(42)
    # Define features
    data = {
        'province_risk': np.random.uniform(0.1, 0.7, n),
        'total_orders': np.random.randint(1, 500, n),
        'product_risk': np.random.uniform(0.1, 0.9, n),
        'distance_km': np.random.uniform(2, 450, n),
        'past_returns': np.random.randint(0, 100, n) # Added 5th feature
    }
    df = pd.DataFrame(data)

    # Logical Labeling (Ground Truth)
    # Risk increases with high province risk, high return ratio, and high product volatility
    ret_ratio = df['past_returns'] / (df['total_orders'] + 1)
    score = (df['province_risk'] * 0.3) + (ret_ratio * 0.5) + (df['product_risk'] * 0.2)
    df['is_return'] = (score > 0.45).astype(int)

    return df

# Initialize Data
print("📊 Generating 100k samples...")
df = generate_massive_dataset()
feature_cols = ['province_risk', 'total_orders', 'product_risk', 'distance_km', 'past_returns']

X = df[feature_cols] # Ensure strict order
y = df['is_return']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ==============================================================================
# PHASE 2: HIGH-PERFORMANCE ML TRAINING
# ==============================================================================
print("🚀 Training XGBoost Model (Production Grade)...")
# Using 'hist' tree method for massive datasets (Amazon SageMaker Style)
model = xgb.XGBClassifier(tree_method='hist', n_estimators=200, max_depth=5, learning_rate=0.05)
model.fit(X_train, y_train)

# ==============================================================================
# PHASE 3: A* LOGISTICS OPTIMIZER
# Concept: f(n) = g(n) + h(n)
# g(n): Fuel/Time cost | h(n): Predicted Risk Penalty
# ==============================================================================
class AStarLogistics:
    def __init__(self, fuel_rate=0.12, return_penalty=45.0):
        self.fuel_rate = fuel_rate        # JOD per KM
        self.return_penalty = return_penalty # Fixed loss if item returns

    def calculate_total_logistics_cost(self, distance, risk_prob):
        # g(n) = Distance Cost
        gn = distance * self.fuel_rate
        # h(n) = Predicted Loss (Risk * Penalty)
        hn = risk_prob * self.return_penalty
        return gn + hn

# ==========================================
# PHASE 4: THE MASTER INFERENCE ENGINE
# ==========================================
def execute_system_v6(order_data):
    # 1. Feature Order Alignment (Fixes the ValueError)
    # We must pass features in the exact order: [prov, total, prod, dist, returns]
    input_vector = np.array([[
        order_data['province_risk'],
        order_data['total_orders'],
        order_data['product_risk'],
        order_data['distance_km'],
        order_data['past_returns']
    ]])

    # 2. Predict Probability
    prob = model.predict_proba(input_vector)[0][1]

    # 3. A* Optimization Logic
    optimizer = AStarLogistics()
    total_cost = optimizer.calculate_total_logistics_cost(order_data['distance_km'], prob)

    # 4. Decision Thresholding (Business Logic)
    # If the combined cost exceeds 35 JOD, we Re-Route to save money/CO2
    decision = "❌ RE-ROUTE TO HUB" if total_cost > 35 else "✅ PROCEED DELIVERY"

    return {
        "Status": "Success",
        "Risk_Probability": f"{prob*100:.2f}%",
        "Total_Logistics_Cost": f"{total_cost:.2f} JOD",
        "Decision": decision,
        "CO2_Avoided": f"{order_data['distance_km'] * 0.21:.2f}kg" if "RE-ROUTE" in decision else "0kg"
    }

# ==========================================
# PHASE 5: LIVE SYSTEM TEST
# ==========================================
# Testing the Aqaba scenario again
aqaba_test = {
    'province_risk': 0.65,
    'total_orders': 50,
    'product_risk': 0.85,
    'distance_km': 350.0,
    'past_returns': 15
}

result = execute_system_v6(aqaba_test)

print("\n" + "="*50)
print("🛡️  AMAZON LOGISTICS INTELLIGENCE (v6.0)")
print("="*50)
for key, value in result.items():
    print(f"{key:<25}: {value}")
print("="*50)

import matplotlib.pyplot as plt

# Get Feature Importance
importance = model.feature_importances_
feature_names = X.columns

# Visualization
plt.figure(figsize=(10, 6))
plt.barh(feature_names, importance, color='orange')
plt.xlabel('Importance Score')
plt.title('Why is ER-Guard making these decisions? (Feature Importance)')
plt.show()

# Print as Text for Quick Analysis
for name, score in zip(feature_names, importance):
    print(f"Feature: {name:<20} | Score: {score:.4f}")

def run_adversarial_audit(model, optimizer):
    print(f"\n{'!'*80}")
    print(f"{'🕵️  AMAZON ER-GUARD: ADVERSARIAL CAPABILITY AUDIT':^80}")
    print(f"{'!'*80}\n")

    scenarios = [
        {
            "name": "High-Risk VIP",
            "desc": "500 orders (Loyal) but buying Volatile Tech to Aqaba.",
            "data": {'province_risk': 0.65, 'total_orders': 500, 'product_risk': 0.90, 'distance_km': 350.0, 'past_returns': 5}
        },
        {
            "name": "The Clean Newbie",
            "desc": "First time customer, safe product, delivery in Amman.",
            "data": {'province_risk': 0.10, 'total_orders': 1, 'product_risk': 0.10, 'distance_km': 5.0, 'past_returns': 0}
        },
        {
            "name": "Proximate Fraud",
            "desc": "Customer 2km away but 90% return history.",
            "data": {'province_risk': 0.10, 'total_orders': 100, 'product_risk': 0.20, 'distance_km': 2.0, 'past_returns': 90}
        },
        {
            "name": "The Balanced Median",
            "desc": "Average customer, average distance, average risk.",
            "data": {'province_risk': 0.30, 'total_orders': 50, 'product_risk': 0.40, 'distance_km': 100.0, 'past_returns': 5}
        }
    ]

    for case in scenarios:
        # Prepare input
        input_v = np.array([[case['data'][col] for col in feature_cols]])
        prob = model.predict_proba(input_v)[0][1]
        cost = optimizer.calculate_total_logistics_cost(case['data']['distance_km'], prob)
        decision = "❌ RE-ROUTE" if cost > 35 else "✅ PROCEED"

        print(f"TEST: {case['name']}")
        print(f"Context: {case['desc']}")
        print(f"AI Probability: {prob*100:.2f}% | Total Cost: {cost:.2f} JOD")
        print(f"VERDICT: {decision}")
        print("-" * 80)

# استدعاء الاختبار
optimizer = AStarLogistics()
run_adversarial_audit(model, optimizer)

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 1. التنبؤ باستخدام بيانات الاختبار (X_test) التي تم عزلها سابقاً
y_pred = model.predict(X_test)

# 2. حساب المقاييس المطلوبة (The Core Metrics)
acc = accuracy_score(y_test, y_pred)
f1  = f1_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
pre = precision_score(y_test, y_pred)

# 3. طباعة النتائج بأسلوب احترافي
print("\n" + "📊" + " " + "="*45)
print(f"{'ER-GUARD MODEL VALIDATION REPORT':^45}")
print("="*47)
print(f"✅ Accuracy (الدقة العامة)    : {acc*100:.2f}%")
print(f"⚖️  F1-Score (الميزان)         : {f1*100:.2f}%")
print(f"🔍 Recall (قوة كشف المرتجع)  : {rec*100:.2f}%")
print(f"🎯 Precision (دقة التوقع)    : {pre*100:.2f}%")
print("="*47)

# 4. التقرير التفصيلي (Classification Report)
print("\n📝 Detailed Report:")
print(classification_report(y_test, y_pred, target_names=['Success ✅', 'Return ❌']))

# 5. رسم مصفوفة الارتباك (Confusion Matrix) لتوضيح النتائج بصرياً

plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Success ✅', 'Return ❌'],
            yticklabels=['Success ✅', 'Return ❌'])
plt.xlabel('AI Prediction')
plt.ylabel('Actual Truth')
plt.title('Logistics Decision: Confusion Matrix')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import xgboost as xgb
# import time
# 
# # --- 1. إجبار المتصفح على الألوان الصحيحة (CSS Force) ---
# st.set_page_config(page_title="Amazon ER-Guard Jordan", layout="wide")
# 
# st.markdown("""
#     <style>
#     /* إجبار الخلفية البيضاء والنصوص الغامقة */
#     .stApp { background-color: #FFFFFF !important; color: #131921 !important; }
# 
#     /* تنسيق الهيدر */
#     .header-style {
#         background-color: #131921;
#         padding: 25px;
#         color: white !important;
#         text-align: center;
#         border-bottom: 5px solid #FF9900;
#         margin-bottom: 20px;
#     }
# 
#     /* تنسيق المدخلات (Input Fields) لتكون واضحة */
#     input, select, .stSelectbox, .stNumberInput {
#         background-color: #f9f9f9 !important;
#         color: #131921 !important;
#         border: 1px solid #FF9900 !important;
#     }
# 
#     /* تنسيق الكبسات البرتقالية (Amazon Button) */
#     .stButton>button {
#         background-color: #FF9900 !important;
#         color: #131921 !important;
#         font-weight: 900 !important;
#         border-radius: 8px !important;
#         border: none !important;
#         height: 3em !important;
#         width: 100% !important;
#         font-size: 1.1rem !important;
#         box-shadow: 0 4px 6px rgba(0,0,0,0.1) !important;
#     }
# 
#     /* تحسين شكل الجدول (Database) */
#     .styled-table { border: 2px solid #eee; border-radius: 10px; }
# 
#     /* إخفاء نصوص الموديل الفنية */
#     .stMetric label { color: #232F3E !important; font-weight: bold; }
#     </style>
# 
#     <div class="header-style">
#         <h1 style="color:white; margin:0;">Amazon ER-Guard System</h1>
#         <p style="color:#FF9900; margin:5px; font-weight:bold; font-size:1.2rem;">📍 JORDAN OPERATIONS HUB</p>
#     </div>
#     """, unsafe_allow_html=True)
# 
# # --- 2. محرك الموديل والترميز (The Engine) ---
# city_map = {"Amman": 1, "Irbid": 2, "Zarqa": 3, "Aqaba": 4, "Ma'an": 5, "Mafraq": 6}
# 
# @st.cache_resource
# def load_ai_engine():
#     X = np.random.rand(50, 5) # (City_Code, Distance, History, Risk, Volume)
#     y = np.random.randint(0, 2, 50)
#     m = xgb.XGBClassifier(n_estimators=20)
#     m.fit(X, y)
#     return m
# 
# model = load_ai_engine()
# 
# if 'db' not in st.session_state:
#     st.session_state.db = []
# 
# # --- 3. واجهة العمليات (Operations) ---
# col_in, col_out = st.columns([1, 1.2], gap="large")
# 
# with col_in:
#     st.markdown("### 📥 Register Shipment")
#     with st.container():
#         with st.form("main_form", clear_on_submit=True):
#             ship_id = st.text_input("Shipment Number", f"JO-{np.random.randint(1000, 9999)}")
#             city = st.selectbox("Destination Province", list(city_map.keys()))
#             dist = st.number_input("Route Distance (KM)", 1, 500, 20)
#             hist = st.slider("Customer Reliability (History)", 0.0, 1.0, 0.05)
# 
#             p_encode = city_map[city] # الترميز
# 
#             if st.form_submit_button("PROCESS & SAVE"):
#                 # حساب الخطورة عبر الموديل
#                 features = np.array([[p_encode, dist, hist, 0.2, 1]])
#                 risk_prob = model.predict_proba(features)[0][1]
# 
#                 # حساب التكلفة (A*)
#                 total_cost = (dist * 0.12) + (risk_prob * 45)
#                 decision = "RE-ROUTE" if total_cost > 35 else "DIRECT"
# 
#                 # إضافة للقاعدة
#                 st.session_state.db.append({
#                     "Order ID": ship_id, "City": city, "ID_Code": p_encode,
#                     "Dist(KM)": dist, "AI_Risk": f"{risk_prob*100:.1f}%",
#                     "Cost(JOD)": f"{total_cost:.2f}", "Decision": decision
#                 })
#                 st.toast("Shipment Logged!", icon="💾")
# 
# with col_out:
#     st.markdown("### 🛡️ AI Audit Result")
#     if st.session_state.db:
#         last = st.session_state.db[-1]
# 
#         # عرض النتائج بوضوح
#         st.info(f"**Audit for:** {last['Order ID']} | **Encoded City:** {last['ID_Code']}")
# 
#         m1, m2 = st.columns(2)
#         m1.metric("Risk Level", last['AI_Risk'])
#         m2.metric("Logistics Cost", f"{last['Cost(JOD)']} JOD")
# 
#         if last['Decision'] == "RE-ROUTE":
#             st.error(f"SYSTEM ALERT: {last['Decision']} (High Risk Path)")
#         else:
#             st.success(f"SYSTEM CLEAR: {last['Decision']} (Profitable Path)")
#     else:
#         st.write("Ready for input. Register a shipment to begin audit.")
# 
# # --- 4. قاعدة البيانات (The Database Table) ---
# st.markdown("---")
# st.markdown("### 📊 Logistics Database (System Log)")
# if st.session_state.db:
#     log_df = pd.DataFrame(st.session_state.db)
#     st.table(log_df) # استخدام Table لضمان الوضوح التام
# 
#     if st.button("🗑️ Reset Database"):
#         st.session_state.db = []
#         st.rerun()
# else:
#     st.write("No records found in database.")
# 
# st.markdown("<br><p style='text-align:center; color:#888;'>Amazon Jordan ER-Guard | Operations Intelligence Unit</p>", unsafe_allow_html=True)

!pip install streamlit -q
!npm install -g localtunnel -q

# 1. الحصول على الـ IP بطريقة بديلة لا تسبب خطأ في الشبكة
import socket
print("Your Password/Endpoint IP is:")
!curl -s https://checkip.amazonaws.com || curl -s https://ifconfig.me

# 2. تشغيل السيرفر والجسر
!streamlit run app.py & npx localtunnel --port 8501

!curl ipv4.icanhazip.com